name: "test"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres
    #     env:
    #       POSTGRES_PASSWORD: postgres
    #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:

    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: "luajit-openresty"

    - uses: leafo/gh-actions-luarocks@master

    - name: build
      run: |
        luarocks install busted
        luarocks install moonscript
        luarocks make

    - name: postgres start
      run: |
        mkdir _postgres
        /usr/lib/postgresql/13/bin/initdb --locale en_US.UTF-8 -E UTF8 -D ./_postgres/
        sudo chown 'runner:runner' /var/run/postgresql
        /usr/lib/postgresql/13/bin/pg_ctl -s -D ./_postgres/ start -w -t 120
        createuser -s -d 'postgres'
        psql -U postgres -c 'select 1'
        make test_db
        make migrate
        busted # -o utfTerminal

    # - name: build
    #   run: |
    #     luarocks install busted
    #     luarocks install moonscript
    #     luarocks make

    # - name: test
    #   run: |
    #     make test_db
    #     make migrate
    #     busted # -o utfTerminal



