name: "test"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres
    #     env:
    #       POSTGRES_PASSWORD: postgres
    #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: postgres
      shell: /bin/sudo -u postgres bash --noprofile --norc -eo pipefail {0}
      run: |
        echo "local all all   trust" >> /etc/postgresql/13/main/pg_hba.conf
        echo "host all all 127.0.0.1/32 trust" >> /etc/postgresql/13/main/pg_hba.conf
        echo "fsync = off" >> /etc/postgresql/13/main/postgresql.conf
        echo "synchronous_commit = off" >> /etc/postgresql/13/main/postgresql.conf
        echo "full_page_writes = off" >> /etc/postgresql/13/main/postgresql.conf
        /usr/lib/postgresql/13/bin/pg_ctl -s -D /var/lib/postgresql/13/main start -w -t 120

    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: "luajit-openresty"

    - uses: leafo/gh-actions-luarocks@master

    - name: build
      run: |
        luarocks install busted
        luarocks install moonscript
        luarocks make

    - name: test
      run: |
        make test_db
        make migrate
        busted # -o utfTerminal



