name: "test"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres
    #     env:
    #       POSTGRES_PASSWORD: postgres
    #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: postgres
      run: |
        mkdir _postgres
        pwd
        /usr/lib/postgresql/13/bin/initdb -D ./_postgres/

        # '/usr/lib/postgresql/13/bin/pg_ctl -s -D /var/lib/postgresql/13/main start -w -t 120'
        # sudo -u postgres sh -c 'echo "local all all   trust" >> /etc/postgresql/13/main/pg_hba.conf'
        # sudo -u postgres sh -c 'echo "host all all 127.0.0.1/32 trust" >> /etc/postgresql/13/main/pg_hba.conf'
        # sudo -u postgres sh -c 'echo "fsync = off" >> /etc/postgresql/13/main/postgresql.conf'
        # sudo -u postgres sh -c 'echo "synchronous_commit = off" >> /etc/postgresql/13/main/postgresql.conf'
        # sudo -u postgres sh -c 'echo "full_page_writes = off" >> /etc/postgresql/13/main/postgresql.conf'
        # sudo -u postgres sh -c 'cp /etc/postgresql/13/main/postgresql.conf /var/lib/postgresql/13/main'
        # sudo -u postgres sh -c 'cp /etc/postgresql/13/main/pg_hba.conf /var/lib/postgresql/13/main'
        # sudo -u postgres sh -c '/usr/lib/postgresql/13/bin/pg_ctl -s -D /var/lib/postgresql/13/main start -w -t 120'

    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: "luajit-openresty"

    - uses: leafo/gh-actions-luarocks@master

    - name: build
      run: |
        luarocks install busted
        luarocks install moonscript
        luarocks make

    - name: test
      run: |
        make test_db
        make migrate
        busted # -o utfTerminal



